version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ../:/var/www/html
        networks:
            default:
                ipv4_address: ${IP_PREFIX}.4

    nginx:
        image: nginx:1.19-alpine
        volumes:
            - ./docker/nginx/templates:/etc/nginx/templates
            - ../:/var/www/html
        environment:
            - APP_FASTCGI_URI=app:9000
            - APP_DOMAIN=${APPLICATION_NAME:-phpimage}.local
        networks:
            default:
                ipv4_address: ${IP_PREFIX}.2
    db:
        image: postgres:13
        environment:
            POSTGRES_PASSWORD: ${APPLICATION_NAME:-phpimage}
            POSTGRES_USER: ${APPLICATION_NAME:-phpimage}
            POSTGRES_DB: ${APPLICATION_NAME:-phpimage}
            TZ: "UTC"
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            default:
                ipv4_address: ${IP_PREFIX}.3

volumes:
    dbdata:
        driver: local

networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: ${IP_PREFIX}.0/24
